import type { NextPage } from "next";
import Head from "next/head";

import { useAtom } from "jotai";

import { itemsAtom } from "../atomStore";

const Home: NextPage = () => {
    const [items] = useAtom(itemsAtom);
    console.log(items);
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4"></main>
        </>
    );
};

export default Home;
